baseurl = "http://elderbrowser.com"
languageCode = "en-us"
title = ""
disqusShortname = "ElderBrowser"
publishdir = "../public"
buildDrafts = true
theme = "hyde"

[params]
Description = "Reading Glasses for the Web"
Copyright = "Copyright &copy; Bean Patch Studios, Inc. 2014"
