baseurl = "http://elderbrowser.com"
languageCode = "en-us"
title = ""
disqusShortname = "ElderBrowser"
publishdir = "../public"
buildDrafts = true
theme = "hyde"

[params]
Description = "Because it's about time"
Copyright = "No thanks."
