name = "Hyde"
license = "MIT"
source_repo = ""
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", ]

[author]
    name = "spf13"
    email = "hugo@spf13.com"
    url = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    url = "http://andhyde.com"
    repo = "http://www.github.com/mdo/hyde"
